  library(magrittr)

Rblpapi::blpConnect()


# Functions -------------------------------------------------------------------------
# Define function to make retrieving Bloomberg data easier/neater
f <- function(tickers, field, type = 'Equity'){
  y <- tickers %>%
    stringr::str_to_upper() %>%
    paste(type) %>%
    Rblpapi::bdp(field) %>%
    dplyr::pull()
  
  return (y)
}

# Define function to calculate growth score
GrowthScore <- function(pam_rank,con_rank,dvd_rank,beta_rank){
  yy <- (pam_rank*.4) + (con_rank*.4) + (dvd_rank*.1) + (beta_rank*.1)
  
  return(yy)
}

# Define function to calculate conservative score
ConservativeScore <- function(pam_rank,con_rank,dvd_rank,beta_rank){
  yy <- (pam_rank + con_rank + beta_rank)*.2 + (dvd_rank*.4) 
  
  return(yy)  
}

# Define rank mapping function
RankMap <- function(rank, n, source.count){
  if(rank == 0){
    return(0)
  } else {
    rank <- 1000 * (1 - (rank - 1)/n)
    return(rank)
  }
}

# Define security ranks by model
SecurityRank <- function(dat, model){
  foo <- dat %>%
    dplyr::arrange(GICS_SECTOR_NAME, desc(RANK)) %>%  # ensures highest ranking securities are in model
    dplyr::mutate(
      CUM_WEIGHT        = cumsum(TARGET_WEIGHT),
      CUM_WEIGHT_ADJ    = dplyr::case_when(
        CUM_WEIGHT > 1 ~ CUM_WEIGHT - 1,
        TRUE ~ 0
      ),
      TARGET_WEIGHT_ADJ = TARGET_WEIGHT - CUM_WEIGHT_ADJ,
      TARGET_WEIGHT_ADJ = dplyr::case_when(
        TARGET_WEIGHT_ADJ < 0 ~ 0,
        TRUE ~ TARGET_WEIGHT_ADJ)) %>%  # Adjusts target weights so that cum sector weight is 100 percent
    dplyr::ungroup() %>%
    dplyr::mutate(
      GICS_SECTOR_NAME       = GICS_SECTOR_NAME %>% stringr::str_to_upper(),
      'Model Name'           = paste(GICS_SECTOR_NAME, '-', model),
      Symbol                 = TICKER %>% stringr::str_to_upper(),
      'Symbol Weight'        = TARGET_WEIGHT_ADJ,
      'Symbol Rank'          = RANK,
      'Legacy Position Flag' = 'No'
    ) %>%
    dplyr::select('Model Name', Symbol, 'Symbol Weight','Symbol Rank','Legacy Position Flag')

  return(foo)
}

# Read in current buy list (generated by outside process)
buylist <- readr::read_csv('buylist.csv', col_types = 'c') %>% dplyr::pull()

# Define current GICS sector weights in the S&P 500
sectorWeights <- c('cond','cons','tels','rlst','inft','hlth','finl','matr','enrs','indu','util') %>%
  stringr::str_to_upper() %>%
  paste0('S5', .) %>%
  paste('Index') %>%
  Rblpapi::bdp(c('GICS_SECTOR_NAME','PERCENT_WEIGHT')) %>%
  dplyr::mutate(
    GICS_SECTOR_WEIGHT = PERCENT_WEIGHT,
    GICS_SECTOR_NAME = c('Consumer Discretionary',
                         'Consumer Staples',
                         'Communication Services',
                         'Real Estate',
                         'Information Technology',
                         'Health Care',
                         'Financials',
                         'Materials',
                         'Energy',
                         'Industrials',
                         'Utilities')
  ) %>%
  dplyr::select(GICS_SECTOR_WEIGHT, GICS_SECTOR_NAME)

dat <- readr::read_csv('./recommendations.txt', col_types = 'cDnnnnnl') %>%  # Generated by outside process
  dplyr::filter(DATE <= Sys.Date()) %>%
  dplyr::arrange(desc(DATE)) %>%
  dplyr::distinct(TICKER, .keep_all = TRUE) %>%  # Keeping only the most recent rec
  dplyr::filter(TICKER %in% buylist) %>% # Removing recs for securities no longer on buy list
  dplyr::mutate(
    # Retrieving data from Bloomberg
    PX_LAST            = TICKER %>% f('PX_LAST'),
    BEST_TARGET_PRICE  = TICKER %>% f('BEST_TARGET_PRICE'),
    EQY_DVD_YLD_IND    = TICKER %>% f('EQY_DVD_YLD_IND'),
    EQY_BETA           = TICKER %>% f('EQY_BETA'),
    GICS_SECTOR_NAME   = TICKER %>% f('GICS_SECTOR_NAME'),
  ) %>%
  # Join GICS sector weights data
  dplyr::left_join(sectorWeights, by = 'GICS_SECTOR_NAME') %>%
  dplyr::group_by(GICS_SECTOR_NAME) %>%
  dplyr::add_count(name = 'SECTOR_PEERS') %>%
  dplyr::mutate(
    # Manipulate data for growth/conservative scoring
    PAM_UPSIDE            = PRICE_TARGET/PX_LAST,
    CONSENSUS_UPSIDE      = BEST_TARGET_PRICE/PX_LAST,
    PAM_UPSIDE_RANK       = PAM_UPSIDE %>% multiply_by(-1) %>% rank(),
    CONSENSUS_UPSIDE_RANK = CONSENSUS_UPSIDE %>% multiply_by(-1) %>% rank(),
    DVD_YLD_RANK          = EQY_DVD_YLD_IND %>% multiply_by(-1) %>% rank(),
    BETA_RANK             = EQY_BETA %>% multiply_by(-1) %>% rank(),
    GROWTH_SCORE          = GrowthScore(PAM_UPSIDE_RANK, 
                                        CONSENSUS_UPSIDE_RANK, 
                                        DVD_YLD_RANK, 
                                        BETA_RANK),
    CONSERVATIVE_SCORE    = ConservativeScore(PAM_UPSIDE_RANK, 
                                              CONSENSUS_UPSIDE_RANK, 
                                              DVD_YLD_RANK, 
                                              BETA_RANK),
    # Rank securities by growth/conservative score
    GROWTH_RANK            = GROWTH_SCORE %>% 
      rank(ties.method = 'first') %>% 
      RankMap(SECTOR_PEERS, sum(SOURCE)) %>% 
      multiply_by(!SOURCE) %>%
      round(0),
    
    CONSERVATIVE_RANK      = CONSERVATIVE_SCORE %>% 
      rank(ties.method = 'first') %>% 
      RankMap(SECTOR_PEERS, sum(SOURCE)) %>% 
      multiply_by(!SOURCE) %>%
      round(0),
    
    # Establish target/max weight in sector model using target for overall portfolio weight
    TARGET_WEIGHT     = .05  %>% 
      divide_by(GICS_SECTOR_WEIGHT) %>% 
      multiply_by(100) %>%
      round(2) %>%
      min(1) %>% 
      multiply_by(!SOURCE),
    
    MAX_WEIGHT        = .10 %>% 
      divide_by(GICS_SECTOR_WEIGHT) %>% 
      multiply_by(100) %>%
      round(2) %>%
      min(1) %>% 
      multiply_by(!SOURCE),
    
    # Removing backslashes (i.e. BRK/B) to match Tamarac formatting
    TICKER = TICKER %>% stringr::str_remove_all('/')
  )

# Adjust target weights using growth rank
dat_growth <- dat %>% 
  dplyr::mutate(RANK = GROWTH_RANK) %>% 
  SecurityRank('Growth')

dat_conservative <- dat %>%
  dplyr::mutate(RANK = CONSERVATIVE_RANK) %>%
  SecurityRank('Conservative')

upload <- dplyr::bind_rows(dat_growth, dat_conservative)

readr::write_csv(upload, 'slm2.csv')

